//
// Generated file, do not edit! Created by opp_msgtool 6.0 from physicallayer/radio/radiopkt/radiopkt.msg.
//

#ifndef __RADIOPKT_M_H
#define __RADIOPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class RadioPkt;
/**
 * Class generated from <tt>physicallayer/radio/radiopkt/radiopkt.msg:16</tt> by opp_msgtool.
 * <pre>
 * packet RadioPkt
 * {
 *     int src;
 *     int dest;
 * 
 *     double positionX;
 *     double positionY;
 *     double carrierFrequency;
 *     double bandwidth;
 * 
 *     double transmitterPowerMW;
 *     double transmitterGainMW;
 * 
 *     int size;
 * }
 * </pre>
 */
class RadioPkt : public ::omnetpp::cPacket
{
  protected:
    int src = 0;
    int dest = 0;
    double positionX = 0;
    double positionY = 0;
    double carrierFrequency = 0;
    double bandwidth = 0;
    double transmitterPowerMW = 0;
    double transmitterGainMW = 0;
    int size = 0;

  private:
    void copy(const RadioPkt& other);

  protected:
    bool operator==(const RadioPkt&) = delete;

  public:
    RadioPkt(const char *name=nullptr, short kind=0);
    RadioPkt(const RadioPkt& other);
    virtual ~RadioPkt();
    RadioPkt& operator=(const RadioPkt& other);
    virtual RadioPkt *dup() const override {return new RadioPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrc() const;
    virtual void setSrc(int src);

    virtual int getDest() const;
    virtual void setDest(int dest);

    virtual double getPositionX() const;
    virtual void setPositionX(double positionX);

    virtual double getPositionY() const;
    virtual void setPositionY(double positionY);

    virtual double getCarrierFrequency() const;
    virtual void setCarrierFrequency(double carrierFrequency);

    virtual double getBandwidth() const;
    virtual void setBandwidth(double bandwidth);

    virtual double getTransmitterPowerMW() const;
    virtual void setTransmitterPowerMW(double transmitterPowerMW);

    virtual double getTransmitterGainMW() const;
    virtual void setTransmitterGainMW(double transmitterGainMW);

    virtual int getSize() const;
    virtual void setSize(int size);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RadioPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RadioPkt& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline RadioPkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<RadioPkt*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __RADIOPKT_M_H

