//
// Generated file, do not edit! Created by opp_msgtool 6.0 from physicallayer/radio/base/RadioPkt.msg.
//

#ifndef __RADIOPKT_M_H
#define __RADIOPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class RadioPkt;
/**
 * Class generated from <tt>physicallayer/radio/base/RadioPkt.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet RadioPkt
 * {
 *     int id;
 *     int src;
 *     int dest;
 *     int size;
 * }
 * </pre>
 */
class RadioPkt : public ::omnetpp::cPacket
{
  protected:
    int id = 0;
    int src = 0;
    int dest = 0;
    int size = 0;

  private:
    void copy(const RadioPkt& other);

  protected:
    bool operator==(const RadioPkt&) = delete;

  public:
    RadioPkt(const char *name=nullptr, short kind=0);
    RadioPkt(const RadioPkt& other);
    virtual ~RadioPkt();
    RadioPkt& operator=(const RadioPkt& other);
    virtual RadioPkt *dup() const override {return new RadioPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getId() const;
    virtual void setId(int id);

    virtual int getSrc() const;
    virtual void setSrc(int src);

    virtual int getDest() const;
    virtual void setDest(int dest);

    virtual int getSize() const;
    virtual void setSize(int size);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RadioPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RadioPkt& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline RadioPkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<RadioPkt*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __RADIOPKT_M_H

