//
// Generated file, do not edit! Created by opp_msgtool 6.0 from linklayer/ieee802154tsch/IEEE802154TSCHAck.msg.
//

#ifndef __IEEE802154TSCHACK_M_H
#define __IEEE802154TSCHACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class IEEE802154TSCHAck;
/**
 * Class generated from <tt>linklayer/ieee802154tsch/IEEE802154TSCHAck.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet IEEE802154TSCHAck
 * {
 *     int seqNum;
 * }
 * </pre>
 */
class IEEE802154TSCHAck : public ::omnetpp::cPacket
{
  protected:
    int seqNum = 0;

  private:
    void copy(const IEEE802154TSCHAck& other);

  protected:
    bool operator==(const IEEE802154TSCHAck&) = delete;

  public:
    IEEE802154TSCHAck(const char *name=nullptr, short kind=0);
    IEEE802154TSCHAck(const IEEE802154TSCHAck& other);
    virtual ~IEEE802154TSCHAck();
    IEEE802154TSCHAck& operator=(const IEEE802154TSCHAck& other);
    virtual IEEE802154TSCHAck *dup() const override {return new IEEE802154TSCHAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IEEE802154TSCHAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IEEE802154TSCHAck& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline IEEE802154TSCHAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<IEEE802154TSCHAck*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IEEE802154TSCHACK_M_H

