//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ietf6tisch/IETF6TiSCHAck.msg.
//

#ifndef __IETF6TISCHACK_M_H
#define __IETF6TISCHACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class IETF6TiSCHAck;
/**
 * Class generated from <tt>ietf6tisch/IETF6TiSCHAck.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet IETF6TiSCHAck
 * {
 *     int seqNum;
 * }
 * </pre>
 */
class IETF6TiSCHAck : public ::omnetpp::cPacket
{
  protected:
    int seqNum = 0;

  private:
    void copy(const IETF6TiSCHAck& other);

  protected:
    bool operator==(const IETF6TiSCHAck&) = delete;

  public:
    IETF6TiSCHAck(const char *name=nullptr, short kind=0);
    IETF6TiSCHAck(const IETF6TiSCHAck& other);
    virtual ~IETF6TiSCHAck();
    IETF6TiSCHAck& operator=(const IETF6TiSCHAck& other);
    virtual IETF6TiSCHAck *dup() const override {return new IETF6TiSCHAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IETF6TiSCHAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IETF6TiSCHAck& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline IETF6TiSCHAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<IETF6TiSCHAck*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IETF6TISCHACK_M_H

