//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ietf6tisch/IETF6TiSCHPkt.msg.
//

#ifndef __IETF6TISCHPKT_M_H
#define __IETF6TISCHPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class IETF6TiSCHPkt;
/**
 * Class generated from <tt>ietf6tisch/IETF6TiSCHPkt.msg:16</tt> by opp_msgtool.
 * <pre>
 * packet IETF6TiSCHPkt
 * {
 *     int src;
 *     int dest;
 *     int seqNum;
 * }
 * </pre>
 */
class IETF6TiSCHPkt : public ::omnetpp::cPacket
{
  protected:
    int src = 0;
    int dest = 0;
    int seqNum = 0;

  private:
    void copy(const IETF6TiSCHPkt& other);

  protected:
    bool operator==(const IETF6TiSCHPkt&) = delete;

  public:
    IETF6TiSCHPkt(const char *name=nullptr, short kind=0);
    IETF6TiSCHPkt(const IETF6TiSCHPkt& other);
    virtual ~IETF6TiSCHPkt();
    IETF6TiSCHPkt& operator=(const IETF6TiSCHPkt& other);
    virtual IETF6TiSCHPkt *dup() const override {return new IETF6TiSCHPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrc() const;
    virtual void setSrc(int src);

    virtual int getDest() const;
    virtual void setDest(int dest);

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IETF6TiSCHPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IETF6TiSCHPkt& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline IETF6TiSCHPkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<IETF6TiSCHPkt*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IETF6TISCHPKT_M_H

