//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ietf6tisch/NetworkLayerPkt.msg.
//

#ifndef __NETWORKLAYERPKT_M_H
#define __NETWORKLAYERPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class NetworkLayerPkt;
/**
 * Class generated from <tt>ietf6tisch/NetworkLayerPkt.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet NetworkLayerPkt
 * {
 *     int src;
 *     int dest;
 *     int seq;
 * }
 * </pre>
 */
class NetworkLayerPkt : public ::omnetpp::cPacket
{
  protected:
    int src = 0;
    int dest = 0;
    int seq = 0;

  private:
    void copy(const NetworkLayerPkt& other);

  protected:
    bool operator==(const NetworkLayerPkt&) = delete;

  public:
    NetworkLayerPkt(const char *name=nullptr, short kind=0);
    NetworkLayerPkt(const NetworkLayerPkt& other);
    virtual ~NetworkLayerPkt();
    NetworkLayerPkt& operator=(const NetworkLayerPkt& other);
    virtual NetworkLayerPkt *dup() const override {return new NetworkLayerPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrc() const;
    virtual void setSrc(int src);

    virtual int getDest() const;
    virtual void setDest(int dest);

    virtual int getSeq() const;
    virtual void setSeq(int seq);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NetworkLayerPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NetworkLayerPkt& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline NetworkLayerPkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<NetworkLayerPkt*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __NETWORKLAYERPKT_M_H

