//
// Generated file, do not edit! Created by opp_msgtool 6.0 from applications/reqres/ReqResPkt.msg.
//

#ifndef __REQRESPKT_M_H
#define __REQRESPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ReqResPkt;
/**
 * Class generated from <tt>applications/reqres/ReqResPkt.msg:16</tt> by opp_msgtool.
 * <pre>
 * packet ReqResPkt
 * {
 *     int senderMACAddress;
 *     simtime_t downSendTime;
 *     simtime_t upSendTime;
 *     int seqNum;
 * }
 * </pre>
 */
class ReqResPkt : public ::omnetpp::cPacket
{
  protected:
    int senderMACAddress = 0;
    omnetpp::simtime_t downSendTime = SIMTIME_ZERO;
    omnetpp::simtime_t upSendTime = SIMTIME_ZERO;
    int seqNum = 0;

  private:
    void copy(const ReqResPkt& other);

  protected:
    bool operator==(const ReqResPkt&) = delete;

  public:
    ReqResPkt(const char *name=nullptr, short kind=0);
    ReqResPkt(const ReqResPkt& other);
    virtual ~ReqResPkt();
    ReqResPkt& operator=(const ReqResPkt& other);
    virtual ReqResPkt *dup() const override {return new ReqResPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSenderMACAddress() const;
    virtual void setSenderMACAddress(int senderMACAddress);

    virtual omnetpp::simtime_t getDownSendTime() const;
    virtual void setDownSendTime(omnetpp::simtime_t downSendTime);

    virtual omnetpp::simtime_t getUpSendTime() const;
    virtual void setUpSendTime(omnetpp::simtime_t upSendTime);

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ReqResPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ReqResPkt& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ReqResPkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<ReqResPkt*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __REQRESPKT_M_H

