//
// Generated file, do not edit! Created by opp_msgtool 6.0 from physicallayer/medium/intarray/IntArray.msg.
//

#ifndef __INTARRAY_M_H
#define __INTARRAY_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class IntArray;
/**
 * Class generated from <tt>physicallayer/medium/intarray/IntArray.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet IntArray
 * {
 *     int data[];
 * }
 * </pre>
 */
class IntArray : public ::omnetpp::cPacket
{
  protected:
    int *data = nullptr;
    size_t data_arraysize = 0;

  private:
    void copy(const IntArray& other);

  protected:
    bool operator==(const IntArray&) = delete;

  public:
    IntArray(const char *name=nullptr, short kind=0);
    IntArray(const IntArray& other);
    virtual ~IntArray();
    IntArray& operator=(const IntArray& other);
    virtual IntArray *dup() const override {return new IntArray(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual void setDataArraySize(size_t size);
    virtual size_t getDataArraySize() const;
    virtual int getData(size_t k) const;
    virtual void setData(size_t k, int data);
    virtual void insertData(size_t k, int data);
    [[deprecated]] void insertData(int data) {appendData(data);}
    virtual void appendData(int data);
    virtual void eraseData(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IntArray& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IntArray& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline IntArray *fromAnyPtr(any_ptr ptr) { return check_and_cast<IntArray*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INTARRAY_M_H

