//
// Generated file, do not edit! Created by opp_msgtool 6.0 from middleware/shmg/messages/BackboneDataInfo.msg.
//

#ifndef __BACKBONEDATAINFO_M_H
#define __BACKBONEDATAINFO_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class BackboneDataInfo;
/**
 * Class generated from <tt>middleware/shmg/messages/BackboneDataInfo.msg:16</tt> by opp_msgtool.
 * <pre>
 * packet BackboneDataInfo
 * {
 *     int mobileNode;
 *     int borderRouter;
 *     int seq;
 *     int rssidBm;
 * }
 * </pre>
 */
class BackboneDataInfo : public ::omnetpp::cPacket
{
  protected:
    int mobileNode = 0;
    int borderRouter = 0;
    int seq = 0;
    int rssidBm = 0;

  private:
    void copy(const BackboneDataInfo& other);

  protected:
    bool operator==(const BackboneDataInfo&) = delete;

  public:
    BackboneDataInfo(const char *name=nullptr, short kind=0);
    BackboneDataInfo(const BackboneDataInfo& other);
    virtual ~BackboneDataInfo();
    BackboneDataInfo& operator=(const BackboneDataInfo& other);
    virtual BackboneDataInfo *dup() const override {return new BackboneDataInfo(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMobileNode() const;
    virtual void setMobileNode(int mobileNode);

    virtual int getBorderRouter() const;
    virtual void setBorderRouter(int borderRouter);

    virtual int getSeq() const;
    virtual void setSeq(int seq);

    virtual int getRssidBm() const;
    virtual void setRssidBm(int rssidBm);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BackboneDataInfo& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BackboneDataInfo& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline BackboneDataInfo *fromAnyPtr(any_ptr ptr) { return check_and_cast<BackboneDataInfo*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __BACKBONEDATAINFO_M_H

