#define RNG_APP_DELAYED_INIT 0
#define RNG_RADIOPKT_RANDOM_ID 1
#define RNG_SHUFFLE 2
#define RNG_CSMA_CA_W 3
#define RNG_MOBILITY_SHUFFLE 4
#define RNG_RADIO_SUCCESS 5
#define RNG_HASHSEED 6
#define RNG_RESCHEDULING 7