//
// Generated file, do not edit! Created by opp_msgtool 6.0 from tsch/tschpkt/tschack.msg.
//

#ifndef __TSCHACK_M_H
#define __TSCHACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TSCHAck;
/**
 * Class generated from <tt>tsch/tschpkt/tschack.msg:16</tt> by opp_msgtool.
 * <pre>
 * packet TSCHAck
 * {
 *     int seqNum;
 * }
 * </pre>
 */
class TSCHAck : public ::omnetpp::cPacket
{
  protected:
    int seqNum = 0;

  private:
    void copy(const TSCHAck& other);

  protected:
    bool operator==(const TSCHAck&) = delete;

  public:
    TSCHAck(const char *name=nullptr, short kind=0);
    TSCHAck(const TSCHAck& other);
    virtual ~TSCHAck();
    TSCHAck& operator=(const TSCHAck& other);
    virtual TSCHAck *dup() const override {return new TSCHAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TSCHAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TSCHAck& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TSCHAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<TSCHAck*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TSCHACK_M_H

