//
// Generated file, do not edit! Created by opp_msgtool 6.0 from application/ConvergecastPkt.msg.
//

#ifndef __CONVERGECASTPKT_M_H
#define __CONVERGECASTPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ConvergecastPkt;
/**
 * Class generated from <tt>application/ConvergecastPkt.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet ConvergecastPkt
 * {
 *     simtime_t sendTime;
 *     int seqNum;
 * }
 * </pre>
 */
class ConvergecastPkt : public ::omnetpp::cPacket
{
  protected:
    omnetpp::simtime_t sendTime = SIMTIME_ZERO;
    int seqNum = 0;

  private:
    void copy(const ConvergecastPkt& other);

  protected:
    bool operator==(const ConvergecastPkt&) = delete;

  public:
    ConvergecastPkt(const char *name=nullptr, short kind=0);
    ConvergecastPkt(const ConvergecastPkt& other);
    virtual ~ConvergecastPkt();
    ConvergecastPkt& operator=(const ConvergecastPkt& other);
    virtual ConvergecastPkt *dup() const override {return new ConvergecastPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(omnetpp::simtime_t sendTime);

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ConvergecastPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ConvergecastPkt& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ConvergecastPkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<ConvergecastPkt*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CONVERGECASTPKT_M_H

