//
// Generated file, do not edit! Created by opp_msgtool 6.0 from applicationpkts/downstreampkt.msg.
//

#ifndef __DOWNSTREAMPKT_M_H
#define __DOWNSTREAMPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DownstreamPkt;
/**
 * Class generated from <tt>applicationpkts/downstreampkt.msg:16</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet DownstreamPkt
 * {
 *     simtime_t upstreamSendTime;
 *     simtime_t sendTime;
 *     int delegateBR;
 *     int mobileNode;
 *     int seqNum;
 * }
 * </pre>
 */
class DownstreamPkt : public ::omnetpp::cPacket
{
  protected:
    omnetpp::simtime_t upstreamSendTime = SIMTIME_ZERO;
    omnetpp::simtime_t sendTime = SIMTIME_ZERO;
    int delegateBR = 0;
    int mobileNode = 0;
    int seqNum = 0;

  private:
    void copy(const DownstreamPkt& other);

  protected:
    bool operator==(const DownstreamPkt&) = delete;

  public:
    DownstreamPkt(const char *name=nullptr, short kind=0);
    DownstreamPkt(const DownstreamPkt& other);
    virtual ~DownstreamPkt();
    DownstreamPkt& operator=(const DownstreamPkt& other);
    virtual DownstreamPkt *dup() const override {return new DownstreamPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual omnetpp::simtime_t getUpstreamSendTime() const;
    virtual void setUpstreamSendTime(omnetpp::simtime_t upstreamSendTime);

    virtual omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(omnetpp::simtime_t sendTime);

    virtual int getDelegateBR() const;
    virtual void setDelegateBR(int delegateBR);

    virtual int getMobileNode() const;
    virtual void setMobileNode(int mobileNode);

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DownstreamPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DownstreamPkt& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DownstreamPkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<DownstreamPkt*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DOWNSTREAMPKT_M_H

